DEFAULT_THEMES = {
    "dark": {
        "name": "Dark Theme",
        "description": "Default dark theme with blue accents",
        "palette": {
            "window": "#2b2b2b",
            "window_text": "#ffffff",
            "base": "#222226",
            "alternate_base": "#323232",
            "text": "#ffffff",
            "button": "#353535",
            "button_text": "#ffffff",
            "bright_text": "#00b4ff",
            "highlight": "#2a82da",
            "highlight_text": "#ffffff",
            "link": "#2a82da",
            "dark": "#1e1e1e",
            "mid": "#3c3c3c",
            "midlight": "#494949",
            "light": "#5c5c5c"
        },
        "editor": {
            "background": "#222226",
            "foreground": "#ffffff",
            "selection_background": "#264f78",
            "selection_foreground": "#ffffff",
            "line_number_background": "#222226",
            "line_number_foreground": "#909090",
            "current_line": "#2a2a2a",
            "search_result": "#613214"
        },
        "syntax": {
            "keyword": "#569cd6",
            "operator": "#d4d4d4",
            "brace": "#d4d4d4",
            "defclass": "#4ec9b0",
            "string": "#ce9178",
            "string2": "#ce9178",
            "comment": "#6a9955",
            "self": "#569cd6",
            "numbers": "#b5cea8",
            "background": "#222226",
            "foreground": "#d4d4d4",
            "functioncall": "#dcdcaa"
        }
    },
    "light": {
        "name": "Light Theme",
        "description": "Default light theme with blue accents",
        "palette": {
            "window": "#f0f0f0",
            "window_text": "#000000",
            "base": "#ffffff",
            "alternate_base": "#f7f7f7",
            "text": "#000000",
            "button": "#e0e0e0",
            "button_text": "#000000",
            "bright_text": "#0000ff",
            "highlight": "#308cc6",
            "highlight_text": "#ffffff",
            "link": "#0000ff",
            "dark": "#a0a0a0",
            "mid": "#b0b0b0",
            "midlight": "#c0c0c0",
            "light": "#d0d0d0"
        },
        "editor": {
            "background": "#ffffff",
            "foreground": "#000000",
            "selection_background": "#add6ff",
            "selection_foreground": "#000000",
            "line_number_background": "#f0f0f0",
            "line_number_foreground": "#707070",
            "current_line": "#f5f5f5",
            "search_result": "#f8e8a0"
        },
        "syntax": {
            "keyword": "#0000ff",
            "operator": "#000000",
            "brace": "#000000",
            "defclass": "#008080",
            "string": "#a31515",
            "string2": "#a31515",
            "comment": "#008000",
            "self": "#0000ff",
            "numbers": "#098658",
            "background": "#ffffff",
            "foreground": "#000000",
            "functioncall": "#795e26"
        }
    },
    "monokai": {
        "name": "Monokai",
        "description": "Dark theme inspired by Monokai",
        "palette": {
            "window": "#272822",
            "window_text": "#f8f8f2",
            "base": "#272822",
            "alternate_base": "#2d2e27",
            "text": "#f8f8f2",
            "button": "#32332b",
            "button_text": "#f8f8f2",
            "bright_text": "#f92672",
            "highlight": "#49483e",
            "highlight_text": "#f8f8f2",
            "link": "#66d9ef",
            "dark": "#1e1f1c",
            "mid": "#3b3c35",
            "midlight": "#474842",
            "light": "#5e5f58"
        },
        "editor": {
            "background": "#272822",
            "foreground": "#f8f8f2",
            "selection_background": "#49483e",
            "selection_foreground": "#f8f8f2",
            "line_number_background": "#272822",
            "line_number_foreground": "#90908a",
            "current_line": "#3e3d32",
            "search_result": "#4a410d"
        },
        "syntax": {
            "keyword": "#f92672",
            "operator": "#f8f8f2",
            "brace": "#f8f8f2",
            "defclass": "#a6e22e",
            "string": "#e6db74",
            "string2": "#e6db74",
            "comment": "#75715e",
            "self": "#fd971f",
            "numbers": "#ae81ff",
            "background": "#272822",
            "foreground": "#f8f8f2",
            "functioncall": "#66d9ef"
        }
    },
    "solarized_dark": {
        "name": "Solarized Dark",
        "description": "Dark theme based on Solarized color scheme",
        "palette": {
            "window": "#002b36",
            "window_text": "#839496",
            "base": "#073642",
            "alternate_base": "#073642",
            "text": "#839496",
            "button": "#073642",
            "button_text": "#839496",
            "bright_text": "#cb4b16",
            "highlight": "#268bd2",
            "highlight_text": "#fdf6e3",
            "link": "#268bd2",
            "dark": "#002b36",
            "mid": "#073642",
            "midlight": "#586e75",
            "light": "#657b83"
        },
        "editor": {
            "background": "#002b36",
            "foreground": "#839496",
            "selection_background": "#073642",
            "selection_foreground": "#93a1a1",
            "line_number_background": "#002b36",
            "line_number_foreground": "#586e75",
            "current_line": "#073642",
            "search_result": "#657b83"
        },
        "syntax": {
            "keyword": "#cb4b16",
            "operator": "#839496",
            "brace": "#839496",
            "defclass": "#b58900",
            "string": "#2aa198",
            "string2": "#2aa198",
            "comment": "#586e75",
            "self": "#d33682",
            "numbers": "#d33682",
            "background": "#002b36",
            "foreground": "#839496",
            "functioncall": "#268bd2"
        }
    },
    "solarized_light": {
        "name": "Solarized Light",
        "description": "Light theme based on Solarized color scheme",
        "palette": {
            "window": "#fdf6e3",
            "window_text": "#657b83",
            "base": "#eee8d5",
            "alternate_base": "#eee8d5",
            "text": "#657b83",
            "button": "#eee8d5",
            "button_text": "#657b83",
            "bright_text": "#cb4b16",
            "highlight": "#268bd2",
            "highlight_text": "#fdf6e3",
            "link": "#268bd2",
            "dark": "#93a1a1",
            "mid": "#839496",
            "midlight": "#93a1a1",
            "light": "#eee8d5"
        },
        "editor": {
            "background": "#fdf6e3",
            "foreground": "#657b83",
            "selection_background": "#eee8d5",
            "selection_foreground": "#586e75",
            "line_number_background": "#fdf6e3",
            "line_number_foreground": "#93a1a1",
            "current_line": "#eee8d5",
            "search_result": "#93a1a1"
        },
        "syntax": {
            "keyword": "#cb4b16",
            "operator": "#657b83",
            "brace": "#657b83",
            "defclass": "#b58900",
            "string": "#2aa198",
            "string2": "#2aa198",
            "comment": "#93a1a1",
            "self": "#d33682",
            "numbers": "#d33682",
            "background": "#fdf6e3",
            "foreground": "#657b83",
            "functioncall": "#268bd2"
        }
    },
    "dracula": {
        "name": "Dracula",
        "description": "Dark theme based on Dracula color scheme",
        "palette": {
            "window": "#282a36",
            "window_text": "#f8f8f2",
            "base": "#282a36",
            "alternate_base": "#282a36",
            "text": "#f8f8f2",
            "button": "#44475a",
            "button_text": "#f8f8f2",
            "bright_text": "#ff79c6",
            "highlight": "#44475a",
            "highlight_text": "#f8f8f2",
            "link": "#8be9fd",
            "dark": "#21222c",
            "mid": "#44475a",
            "midlight": "#6272a4",
            "light": "#6272a4"
        },
        "editor": {
            "background": "#282a36",
            "foreground": "#f8f8f2",
            "selection_background": "#44475a",
            "selection_foreground": "#f8f8f2",
            "line_number_background": "#282a36",
            "line_number_foreground": "#6272a4",
            "current_line": "#44475a",
            "search_result": "#6272a4"
        },
        "syntax": {
            "keyword": "#ff79c6",
            "operator": "#f8f8f2",
            "brace": "#f8f8f2",
            "defclass": "#50fa7b",
            "string": "#f1fa8c",
            "string2": "#f1fa8c",
            "comment": "#6272a4",
            "self": "#bd93f9",
            "numbers": "#bd93f9",
            "background": "#282a36",
            "foreground": "#f8f8f2",
            "functioncall": "#8be9fd"
        }
    },
    "nord": {
        "name": "Nord",
        "description": "Dark theme based on Nord color scheme",
        "palette": {
            "window": "#2e3440",
            "window_text": "#d8dee9",
            "base": "#3b4252",
            "alternate_base": "#434c5e",
            "text": "#d8dee9",
            "button": "#434c5e",
            "button_text": "#d8dee9",
            "bright_text": "#88c0d0",
            "highlight": "#5e81ac",
            "highlight_text": "#eceff4",
            "link": "#88c0d0",
            "dark": "#2e3440",
            "mid": "#3b4252",
            "midlight": "#434c5e",
            "light": "#4c566a"
        },
        "editor": {
            "background": "#2e3440",
            "foreground": "#d8dee9",
            "selection_background": "#4c566a",
            "selection_foreground": "#eceff4",
            "line_number_background": "#2e3440",
            "line_number_foreground": "#4c566a",
            "current_line": "#3b4252",
            "search_result": "#5e81ac"
        },
        "syntax": {
            "keyword": "#81a1c1",
            "operator": "#d8dee9",
            "brace": "#d8dee9",
            "defclass": "#8fbcbb",
            "string": "#a3be8c",
            "string2": "#a3be8c",
            "comment": "#4c566a",
            "self": "#b48ead",
            "numbers": "#b48ead",
            "background": "#2e3440",
            "foreground": "#d8dee9",
            "functioncall": "#88c0d0"
        }
    }
}